import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Button} from 'semantic-ui-react'
import {client} from '../utils/shopify'

export default function Home(products) {
  console.log({products})
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button color = 'purple'>Shop</Button>
    </div>
  )
}

export async function getServerSideProps(){
  const products = await client.product.fetchAll();
  console.log("Homepage")
  return {props:{products: JSON.parse(JSON.stringify(products))}}
}